---
title: "plm"
output: html_document
date: "2023-07-27"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/jessiejzhou/network-storage/WNV/sjv-wnv")
library(sf)
library(plm)
library(margins)
library(car)
library(glmnet)
library(dplyr)
set.seed(123)
```

## Loading/Prepping Data
```{r}
# plotting shapefile
sf <- st_read("Data/weekly/clusterPolys_2_23_update.shp")

# getting lat/long
coords <- sf %>%
  st_transform(4326) %>%
  mutate(centroids = st_centroid(geometry),
         long = st_coordinates(centroids)[,1],
         lat = st_coordinates(centroids)[,2]) %>%
  dplyr::select(-centroids)

clusters <- spatial_block_cv(coords, method = "random", n = 30, relevant_only = T, v = 5)

splits_df <- data.frame()
for (i in 1:5) {
  new_df <- assessment(clusters$splits[[i]])
  new_df$fold <- i
  splits_df <- rbind(splits_df, new_df)  # Bind all points and fold IDs together
}

splits_df <- st_drop_geometry(splits_df)
splits_df <- distinct(splits_df, clust, .keep_all = TRUE)

```

```{r}
MIRPIR <- read.csv("Data/weekly/wnvMIRPIR1500LagWeeks0.csv")
```

```{r}
MIRPIR_2 <- MIRPIR %>%
  merge(splits_df, by = "clust") %>%
  mutate(MIRAll = ifelse(MIRAll > 0, 1, 0)) %>% 
  # Months since June 2010 (first month)
  mutate(Month = (substr(Date, 6, 7) %>% as.integer()) + 12 * (year-2010)) %>%
  mutate(week = ifelse(length(wy) == 6, substr(wy, 6, 6), substr(wy, 6, 7) %>% as.numeric()),
         # weeks since first week
         w = woy + 52 * (year - 2010)) %>%
  ungroup() 

```

```{r}
split <- initial_split(MIRPIR_2, prop = 0.8, strata = MIRAll)
MIRPIR_train <- training(split)
MIRPIR_test <- testing(split)

ptrain <- pdata.frame(MIRPIR_train, index = c("clust", "w"))
ptest <- pdata.frame(MIRPIR_test, index = c("clust", "w"))

mir <- ptrain[c("MIRAll", "fold", "chirpsMean" , "Humidity.Max" , "Humidity.Min" , "Specific.Humidity" ,
  "Temp.Max.K" , "Temp.Min.K" , "VPD.kPa" , "Precip.Mean.mm...day" , "NDVI" , "jrcStandingWater" , "irrWater" ,
  "eddi14d" , "eddi180d" , "eddi1y" , "eddi270d" , "eddi2y" , "eddi30d" , "eddi5y" , "eddi90d" , "pdsi" ,
  "spei14d" , "spei180d" , "spei1y" , "spei270d" , "spei2y" , "spei30d" , "spei5y" , "spei90d" , "spi14d" , "spi180d" , "spi1y" , "spi270d" , "spi2y" , "spi30d" , "spi5y" , "spi90d" , "z" , "lat" , "long")]

mir <- mir[sample(1:nrow(mir)), ] %>%
  na.omit() 

```

```{r, fig.height=16, fig.width=16}
plm_performance  <-  data.frame(model  =  rep("PLM", 5),
                               fold_id  =  1:5,
                               RMSE  =  rep(NA, 5),
                               MAE  =  rep(NA, 5))
```

```{r, fig.height=16, fig.width=16}
corrPlotFn <- function(data) {
  numeric_vars <- sapply(data, is.numeric)
  numeric_data <- data[, numeric_vars]

  corr_matrix <- cor(numeric_data)

  corrplot(corr_matrix, type = 'lower', diag = FALSE, method = 'number')
}
corrPlotFn(mir[,46:nrow("mir")])
```

## Performign CV
```{r}
form <- MIRAll ~ chirpsMean + Humidity.Max + Humidity.Min + Specific.Humidity +
  Temp.Max.K + Temp.Min.K + VPD.kPa + Precip.Mean.mm...day + NDVI + jrcStandingWater + irrWater +
  eddi14d + eddi180d + eddi1y + eddi270d + eddi2y + eddi30d + eddi5y + eddi90d + pdsi +
  spei14d + spei180d + spei1y + spei270d + spei2y + spei30d + spei5y + spei90d + spi14d + spi180d + spi1y + spi270d + spi2y + spi30d + spi5y + spi90d + z + lat + long

for (i in 1:5) {
  
  train <- mir[mir$fold != i,]; train <- train[-2]
  test <- mir[mir$fold == i,]; test <- test[-2]
  
    
    model <- plm(formula = form,
                    data = train,
                    model = "pooling")
    
   pred0 <- predict(model)
   rmse <- sqrt(mean((pred0 - train$MIRAll)^2))
   mae <- mean(abs(pred0 - train$MIRAll))
  
  plm_performance[i, "RMSE"] <- rmse
  plm_performance[i, "MAE"] <- mae
  
}

```


```{r}
model1_vif <- data.frame(importance = vif(model), var = names(mir[,-c(1,2)]))
ggplot(model1_vif, aes(x = reorder(var, -importance), y = importance)) + 
  geom_bar(stat = "identity") + 
  coord_flip()
```

# Regularized Regression

To adjust for high collinearity

```{r}
glm_train <- ptrain %>%
  dplyr::select(clust,w,fold,MIRAll, chirpsMean:lat) 
glm_test <- ptest %>%
  dplyr::select(clust,w,fold,MIRAll, chirpsMean:lat)

glm_train <- glm_train[sample(1:nrow(glm_train)), ]

glmnet_performance  <-  data.frame(model  =  rep("GLMNET", 5),
                               fold_id  =  1:5,
                               RMSE  =  rep(NA, 5),
                               MAE  =  rep(NA, 5),
                               lambda =  rep(NA, 5))
```

```{r}
for (i in 1:5) {
  
  train <- glm_train[glm_train$fold != i,]; train <- train[,-c(1:3)]
  test <- glm_train[glm_train$fold == i,]; test <- test[,-c(1:3)]
  
  train_complete <- train[complete.cases(train), ]
  test_complete  <-  test[complete.cases(test), ]
  
  x_train <- as.matrix(train_complete[,-1])
  y_train <- train_complete[,1]
  
  cv_model <- cv.glmnet(x_train, y_train, alpha = 1)
  best_lambda <- cv_model$lambda.min
  best_model <- glmnet(x_train, y_train, alpha = 1, lambda = best_lambda)
  
  x_test <- as.matrix(test_complete[,-1])
  pred0 <- predict(best_model, newx = x_test)
  
  rmse <- sqrt(mean((pred0 - test_complete$MIRAll)^2))
  mae <- mean(abs(pred0 - test_complete$MIRAll))
  
  glmnet_performance[i, "RMSE"] <- rmse
  glmnet_performance[i, "MAE"] <- mae
  glmnet_performance[i, "lambda"] <- best_lambda
  
  
}
```



# testing data
```{r}
glm_train2 <- glm_train[complete.cases(glm_train),]

final_x <- as.matrix(glm_train2[,-c(1:4)]) 
final_y <- as.matrix(glm_train2[4])

glm_test2 <- glm_test[complete.cases(glm_test),] 
test_x <- as.matrix(glm_test2[,-c(1:4)]) 
  
final_model <- glmnet(final_x, final_y,alpha = 1, 
                      lambda = mean(glmnet_performance$lambda))

plot(final_model)


```

```{r}
glmnet_pred <- predict(final_model, newx = test_x)

```







