---
title: "sdm_weekly"
output: html_document
date: "2023-07-16"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/jessiejzhou/network-storage/WNV/sjv-wnv")
library(ranger)
library(rsample)
library(spatialsample)
library(dplyr)
library(pROC)
library(rgdal)
library(sdm)
library(sf)
library(ggplot2)
library(pscl)
library(corrplot)
library(xts)
library(ISOweek)
library(sf)
library(glmnet)
set.seed(123)
```

# Surveilance data

## eda
```{r}
tarsalis1500 <- read.csv("Data/weekly/tarsalisFemale1500LagWeeks0.csv")
```

```{r, fig.height=16, fig.width=16}
corrPlotFn <- function(data) {
  numeric_vars <- sapply(data, is.numeric)
  numeric_data <- data[, numeric_vars]
  numeric_data <- na.omit(numeric_data)

  corr_matrix <- cor(numeric_data)

  corrplot(corr_matrix, type = 'lower', diag = FALSE, method = 'color')
}

corrPlotFn(tarsalis1500)
```

# Trying TS
```{r}
tarsalis.ts <- tarsalis1500[c("Date", "totalMosquitoes")]
tarsalis.ts <- tarsalis.ts %>%
  na.omit()
tarsalis.ts$Date <- as.Date(tarsalis.ts$Date, format = "%Y-%m-%d")
tarsalis..ts <- ts(tarsalis.ts$totalMosquitoes, start = c(2010,1,5), frequency = 52)
```

# SDM

```{r}
# plotting shapefile
sf <- read_sf("Data/weekly/clusterPolys_2_23_update.shp")
plot(sf)
```


```{r}
tarsalis_split <- initial_split(tarsalis1500, prop = 0.8, strata = clust)
tarsalis_train <- training(tarsalis_split)
tarsalis_test <- testing(tarsalis_split)
```

```{r}
# getting lat/long
coords <- sf %>%
  st_transform(4326) %>%
  mutate(centroids = st_centroid(geometry),
         long = st_coordinates(centroids)[,1],
         lat = st_coordinates(centroids)[,2]) %>%
  select(-centroids)

clusters <- spatial_block_cv(coords, method = "random", n = 30, relevant_only = T, v = 5)

splits_df <- data.frame()
for (i in 1:5) {
  new_df <- assessment(clusters$splits[[i]])
  new_df$fold <- i
  splits_df <- rbind(splits_df, new_df)  # Bind all points and fold IDs together
}

splits_df <- st_drop_geometry(splits_df)
splits_df <- distinct(splits_df, clust, .keep_all = TRUE)

tarsalis_train2 <- merge(tarsalis_train, splits_df, by ="clust")
```

```{r}
tarsalis2 <- tarsalis_train2[c("totalMosquitoes", "fold", "Humidity.Max", "Humidity.Min", "Specific.Humidity", "Temp.Max.K", "Temp.Min.K", "VPD.kPa", "Precip.Mean.mm...day", "EVI", "NDVI", "jrcStandingWater")]
tarsalis2 <- tarsalis2[sample(1:nrow(tarsalis2)), ]
tarsalis2 <- na.omit(tarsalis2)

# df for results of each fold, 5-fold cv
glm_performance  <-  data.frame(model  =  rep("GLM", 5),
                               fold_id  =  1:5,
                               RMSE  =  rep(NA, 5),
                               MAE  =  rep(NA, 5),
                               totalMosquitoes  =  rep(NA, 5),    
                               background  =  rep(NA, 5))

```

## glm 
```{r}
for (i in 1:5) {
  
  train <- tarsalis2[tarsalis2$fold != i,]; train <- train[-2]
  test <- tarsalis2[tarsalis2$fold == i,]; test <- test[-2]
  
    
    model <- glm(formula = totalMosquitoes ~ .,
                    data = train,
                    family = poisson(link = 'log'))
  
   pred0 <- predict(model, newdata = test, type = "response")
   rmse <- sqrt(mean((pred0 - test$totalMosquitoes)^2))
   mae <- mean(abs(pred0 - test$totalMosquitoes))
  
  glm_performance[i, "RMSE"] <- rmse
  glm_performance[i, "MAE"] <- mae
  glm_performance[i, "totalMosquitoes"] <- sum(test$totalMosquitoes)
  glm_performance[i, "background"] <- sum(test$totalMosquitoes == 0)
  
}
```

```{r}
tarsalis_test <- na.omit(tarsalis_test)

final_tarsalis_model <- glm(formula = totalMosquitoes ~ . ,
                        data = tarsalis2[-2],
                        family = poisson(link = "log"))

pred1 <- predict(final_tarsalis_model, newdata = tarsalis_test, type = "response")
data.frame(pred1)
summary(pred1)
```


## Regularized regression
```{r}
glmnet_performance  <-  data.frame(model  =  rep("GLMNET", 5),
                               fold_id  =  1:5,
                               RMSE  =  rep(NA, 5),
                               MAE  =  rep(NA, 5),
                               totalMosquitoes  =  rep(NA, 5),    
                               background  =  rep(NA, 5),
                               lambda = rep(NA, 5))
```

```{r}
for (i in 1:5) {
  train <- tarsalis2[tarsalis2$fold != i, ]
  test <- tarsalis2[tarsalis2$fold == i, ]

  x_train <- as.matrix(train[, -c(1, 2)])
  y_train <- train$totalMosquitoes
  x_test <- as.matrix(test[, -c(1, 2)])
  y_test <- test$totalMosquitoes
  
  fit <- glmnet(x_train, y_train, family = "poisson")
  
  cv_fit <- cv.glmnet(x_train, y_train, family = "poisson")
  best_lambda <- cv_fit$lambda.min
  
  glmnet_performance[i, "lambda"] <- best_lambda
  
  pred0 <- predict(fit, newx = x_test, type = "response", s = best_lambda)
  
  rmse <- sqrt(mean((pred0 - y_test)^2))
  mae <- mean(abs(pred0 - y_test))
  
  
  # Store results in the dataframe
  glmnet_performance[i, "RMSE"] <- rmse
  glmnet_performance[i, "MAE"] <- mae
  glmnet_performance[i, "totalMosquitoes"] <- sum(y_test)
  glmnet_performance[i, "background"] <- sum(y_test == 0)
}
```


# MIRPIR data
```{r}
mir1500 <- read.csv("Data/weekly/wnvMIRPIR1500LagWeeks0.csv")
```


```{r}
mir_split <- initial_split(mir1500, prop = 0.8, strata = clust)
mir_train <- training(mir_split)
mir_test <- testing(mir_split)
mir_train2 <- merge(mir_train, splits_df, by ="clust")
```

```{r}
mir <- mir_train2[c("MIRAll", "fold", "Humidity.Max", "Humidity.Min", "Specific.Humidity", "Temp.Max.K", "Temp.Min.K", "VPD.kPa", "Precip.Mean.mm...day", "EVI", "NDVI", "jrcStandingWater")]
mir <- mir[sample(1:nrow(mir)), ] %>%
  na.omit()

# df for results of each fold, 5-fold cv
mir_glm_performance  <-  data.frame(model  =  rep("GLM", 5),
                               fold_id  =  1:5,
                               RMSE  =  rep(NA, 5),
                               MAE  =  rep(NA, 5),
                               MIR  =  rep(NA, 5),    
                               background  =  rep(NA, 5))

```

GLM Model
```{r}
for (i in 1:5) {
  
  train <- mir[mir$fold != i,]; train <- train[-2]
  test <- mir[mir$fold == i,]; test <- test[-2]
  
    
    model <- glm(formula = MIRAll ~ .,
                    data = train,
                    family = gaussian)
  
   pred0 <- predict(model, newdata = test, type = "response")
   rmse <- sqrt(mean((pred0 - test$MIRAll)^2))
   mae <- mean(abs(pred0 - test$MIRAll))
  
  mir_glm_performance[i, "RMSE"] <- rmse
  mir_glm_performance[i, "MAE"] <- mae
  
}
```


Trying rf model
```{r}
rf_performance  <-  data.frame(model  =  rep("RF", 5),
                               fold_id  =  1:5,
                               auc  =  rep(NA, 5))

hypergrid_final  <-  data.frame(mtry  =  rep(NA,5), 
                                node_size = rep(NA, 5), 
                                sample_size  =  rep(NA, 5))
```

```{r}
for(i  in  1:5){ 
    
    train  <-  mir[mir$fold !=  i, ];  train  <-  train[-2]
    test  <-  mir[mir$fold ==  i, ];  test  <-  test[-2]
  

    hyper_grid  <-  expand.grid(
        mtry =  seq(1, 10, by  =  1), 
        node_size =  seq(1,4, by  =  1),    
        sample_size  =  c(.6, .70, .80),   
        OOB_RMSE =  0
    )

    for(j  in  1:nrow(hyper_grid)){
        
        model  <-  ranger(
            formula  =  MIRAll  ~  .,    
            data  =  train,    
            num.trees  =  2000,  
            mtry  =  hyper_grid$mtry[j],
            min.node.size  =  hyper_grid$node_size[j],  
            sample.fraction  =  hyper_grid$sample_size[j], 
            probability  =  TRUE, 
            replace = TRUE,
            splitrule = "extratrees",
            seed  =  123
            )
        
        hyper_grid$OOB_RMSE[j]  <-  sqrt(model$prediction.error)
    }
    
    hyper_grid2  <-  hyper_grid  %>%  
        dplyr::arrange(OOB_RMSE)
    
    #train  model
    train_model  <-  ranger(
        formula  =  MIRAll  ~  .,    
        data  =  train,   
        num.trees  =  2000,  
        mtry  =  hyper_grid2$mtry[1], auc <- roc(response = y_test, predictor = pred0, levels = c(0, 1), auc = TRUE)
}

        min.node.size  =  hyper_grid2$node_size[1], 
        sample.fraction  =  hyper_grid2$sample_size[1],
        probability  =  TRUE, 
        replace = TRUE,
        splitrule = "extratrees",
        seed  =  123)
    
    #save  model  performance  results
    pred0  <-  predict(train_model, data=test);  pred  <-  pred0$predictions[,1]
    auc  <-  pROC::roc(response=test[,"presence"], predictor=pred, levels=c(0, 1), auc  =  TRUE)
    rf_performance[i, "auc"]  <-  auc$auc
    
    hypergrid_final[i, "mtry"]  <-  hyper_grid2$mtry[1]
    hypergrid_final[i, "node_size"]  <-  hyper_grid2$node_size[1]
    hypergrid_final[i, "sample_size"]  <-  hyper_grid2$sample_size[1]

}

```















